const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const InventoryModel = require('../models/InventoryModel');
const BorrowModel = require('../models/BorrowModel');
const ReturnModel = require('../models/ReturnModel');
const SupplierModel = require('../models/SupplierModel');
const TransferModel = require('../models/TransferModel');
const DisposalModel = require('../models/DisposalModel');
const MaintenanceModel = require('../models/MaintenanceModel');
const pool = require('../config/database');
const { sendSuccess, sendError } = require('../utils/response');
const { parseReportFilters, parseInventoryReportFilters } = require('../utils/reportFilters');
const {
  validateConsumableFilter,
  shouldExcludeConsumableFromLists
} = require('../utils/assetClassification');
const {
  getReportAccessScope,
  getInventoryAccessScope,
  applyReportDepartmentScope
} = require('../utils/roleHelpers');
const { buildReportPayload, buildReportSummary, buildExportHeaderMeta, resolveDepartmentLabel, formatDisplayDate } = require('../utils/reportSummaryService');
const { CONDITION_OPTIONS } = require('../utils/conditionOptions');
const {
  emptyListResult,
  queryWithOptionalPagination,
  parseListPagination
} = require('../utils/listPagination');

const INVENTORY_REPORT_DATE_EXPR = 'COALESCE(i.acquisition_date, DATE(i.created_at))';

function formatExportCellDate(value) {
  if (value == null || value === '') return '';
  return formatDisplayDate(value);
}

/**
 * Inventory/Asset Status export table.
 * Department / Location / Custodian stay in the header when uniform;
 * otherwise they remain as table columns so data is not lost.
 */
function buildInventoryExportTable(items = [], headerMeta = {}, options = {}) {
  const includeStatusFields = options.includeClassificationConditionStatus !== false;
  const headers = [
    'Property Tag',
    'Item Code',
    'Item Name',
    'Brand'
  ];
  if (includeStatusFields) {
    headers.push('Classification', 'Condition', 'Status');
  }
  headers.push('Acquisition Date');

  const includeDepartment = !headerMeta.department;
  const includeLocation = !headerMeta.location;
  const includeCustodian = !headerMeta.custodian;

  // Category in this system maps to department; only show when not already in header.
  if (includeDepartment) headers.splice(4, 0, 'Department');
  if (includeLocation) headers.push('Location');
  if (includeCustodian) headers.push('Custodian');

  const rows = items.map((i) => {
    const row = [
      i.property_tag || '',
      i.item_code || '',
      i.item_name || '',
      i.brand || ''
    ];
    if (includeDepartment) row.push(i.department_name || i.category_name || '');
    if (includeStatusFields) {
      row.push(
        i.asset_classification || '',
        i.condition || '',
        i.status || ''
      );
    }
    row.push(formatExportCellDate(i.acquisition_date));
    if (includeLocation) row.push(i.location_name || '');
    if (includeCustodian) row.push(i.custodian_name || '');
    return row;
  });

  return { headers, rows };
}

function buildExportMetaColumns(headerMeta = {}) {
  const col1 = [];
  const col2 = [];
  const col3 = [];

  if (headerMeta.department) col1.push(['Department', headerMeta.department]);
  if (headerMeta.location) col1.push(['Location', headerMeta.location]);

  if (headerMeta.custodian) col2.push(['Custodian', headerMeta.custodian]);
  if (headerMeta.generated_by) col2.push(['Generated By', headerMeta.generated_by]);

  col3.push(['Date Generated', headerMeta.generated_at_label || formatDisplayDate(new Date())]);
  col3.push(['Total Records', String(headerMeta.total_records ?? 0)]);
  if (headerMeta.date_range?.from || headerMeta.date_range?.to) {
    col3.push([
      'Date Range',
      `${headerMeta.date_range.from || '—'} to ${headerMeta.date_range.to || '—'}`
    ]);
  }

  // If a column is empty (e.g. no dept/location), rebalance leftover fields.
  const all = [...col1, ...col2, ...col3];
  if (!col1.length || !col2.length) {
    const balanced = [[], [], []];
    all.forEach((pair, index) => {
      balanced[index % 3].push(pair);
    });
    return balanced;
  }

  return [col1, col2, col3];
}

/**
 * Compact 3-column metadata block for PDF exports.
 * Reduces vertical space while keeping labels readable.
 */
function writePdfExportHeader(doc, headerMeta) {
  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const usableWidth = right - left;

  doc.font('Helvetica-Bold').fontSize(12)
    .text('CAVITE INSTITUTE PROPERTY MANAGEMENT SYSTEM', left, doc.y, {
      width: usableWidth,
      align: 'center'
    });
  doc.moveDown(0.25);
  doc.font('Helvetica-Bold').fontSize(11)
    .text(String(headerMeta.title || 'Report').toUpperCase(), left, doc.y, {
      width: usableWidth,
      align: 'center'
    });
  doc.moveDown(0.55);

  const columnItems = buildExportMetaColumns(headerMeta);
  const columns = 3;
  const gap = 12;
  const colWidth = (usableWidth - gap * (columns - 1)) / columns;
  const fontSize = 8;
  const startY = doc.y;
  let maxBottom = startY;

  columnItems.forEach((items, colIndex) => {
    let y = startY;
    const x = left + colIndex * (colWidth + gap);
    items.forEach(([label, value]) => {
      const line = `${label} : ${value || '—'}`;
      doc.font('Helvetica').fontSize(fontSize)
        .text(line, x, y, { width: colWidth });
      y += doc.heightOfString(line, { width: colWidth }) + 6;
    });
    maxBottom = Math.max(maxBottom, y);
  });

  const dividerY = maxBottom + 2;
  doc.moveTo(left, dividerY).lineTo(right, dividerY).strokeColor('#888888').lineWidth(0.5).stroke();
  doc.strokeColor('#000000').lineWidth(1);
  doc.y = dividerY + 12;
}

/**
 * Compact 3-column metadata block for Excel exports.
 */
function writeExcelExportHeader(sheet, headerMeta) {
  sheet.addRow(['CAVITE INSTITUTE PROPERTY MANAGEMENT SYSTEM']);
  sheet.addRow([String(headerMeta.title || 'Report').toUpperCase()]);
  sheet.addRow([]);

  const columnItems = buildExportMetaColumns(headerMeta);
  const maxRows = Math.max(
    columnItems[0].length,
    columnItems[1].length,
    columnItems[2].length,
    1
  );

  for (let i = 0; i < maxRows; i += 1) {
    const rowValues = columnItems.map((items) => {
      const pair = items[i];
      return pair ? `${pair[0]} : ${pair[1]}` : '';
    });
    const metaRow = sheet.addRow(rowValues);
    metaRow.font = { size: 10 };
    metaRow.alignment = { vertical: 'top', wrapText: true };
  }

  sheet.addRow([]);

  sheet.getRow(1).font = { bold: true, size: 14 };
  sheet.getRow(1).alignment = { horizontal: 'center' };
  sheet.getRow(2).font = { bold: true, size: 12 };
  sheet.getRow(2).alignment = { horizontal: 'center' };
}

function autofitExcelColumns(sheet) {
  const colCount = sheet.columnCount || 1;
  for (let i = 1; i <= colCount; i += 1) {
    const col = sheet.getColumn(i);
    let maxLength = 12;
    col.eachCell({ includeEmpty: true }, (cell) => {
      const value = cell.value == null ? '' : String(cell.value);
      maxLength = Math.max(maxLength, Math.min(value.length + 2, 40));
    });
    col.width = maxLength;
  }
}

function shouldUseLandscape(headers = []) {
  // Portrait by default; landscape only when there are too many columns.
  return Array.isArray(headers) && headers.length > 8;
}

function getFilters(query) {
  const filters = parseReportFilters(query);
  const filterError = validateConsumableFilter(filters.asset_classification);
  if (filterError) {
    const err = new Error(filterError);
    err.statusCode = 400;
    throw err;
  }
  if (shouldExcludeConsumableFromLists()) {
    filters.exclude_consumable = true;
  }
  return filters;
}

function getScopedReportFilters(query, user) {
  const filters = getFilters(query);
  const scope = getReportAccessScope(user);
  filters.scope = scope;
  applyReportDepartmentScope(filters, scope);
  return filters;
}

function getBorrowReportFilters(query, user) {
  return getScopedReportFilters(query, user);
}

function getInventoryReportFilters(query, user) {
  const filters = parseInventoryReportFilters(query);
  const filterError = validateConsumableFilter(filters.asset_classification);
  if (filterError) {
    const err = new Error(filterError);
    err.statusCode = 400;
    throw err;
  }
  if (shouldExcludeConsumableFromLists()) {
    filters.exclude_consumable = true;
  }
  // Same visibility as Inventory page: custodians by assigned custodian_id (any department).
  const scope = getInventoryAccessScope(user);
  filters.scope = scope;
  applyReportDepartmentScope(filters, scope);
  filters.date_column = INVENTORY_REPORT_DATE_EXPR;
  return filters;
}

function normalizeListRows(result) {
  return Array.isArray(result) ? result : (result?.data || []);
}

async function sendReportSuccess(res, reportType, rows, filters = {}) {
  const payload = await buildReportPayload(reportType, rows, filters);
  sendSuccess(res, payload);
}

function wantsReportPagination(query = {}) {
  return query.page !== undefined && query.page !== null && query.page !== '';
}

async function sendPaginatedListReport(res, reportType, filters, query, {
  fetchRows,
  fetchAggregates = null
}) {
  if (filters?.department_scope_mismatch) {
    await sendReportSuccess(res, reportType, [], filters);
    return;
  }

  if (!wantsReportPagination(query)) {
    const result = await fetchRows(filters);
    await sendReportSuccess(res, reportType, normalizeListRows(result), filters);
    return;
  }

  filters.paginated = true;
  filters.page = query.page;
  filters.limit = query.limit || 25;

  const [pageResult, aggregates, departmentLabel] = await Promise.all([
    fetchRows(filters),
    fetchAggregates
      ? fetchAggregates(filters)
      : Promise.resolve(null),
    resolveDepartmentLabel(filters)
  ]);

  const rows = normalizeListRows(pageResult);
  const total = aggregates?.total != null
    ? Number(aggregates.total)
    : Number(pageResult?.total ?? rows.length);
  const page = Number(pageResult?.page || parseListPagination(filters)?.page || 1);
  const limit = Number(pageResult?.limit || parseListPagination(filters)?.limit || 25);
  const totalPages = Math.max(1, Math.ceil(total / limit) || 1);

  const summary = buildReportSummary(reportType, [], filters, {
    departmentLabel,
    total_records: total,
    status_breakdown: aggregates?.status_breakdown || {},
    department_breakdown: aggregates?.department_breakdown || {}
  });

  if (reportType === 'custodians' && aggregates?.total_assigned_assets != null) {
    summary.total_assigned_assets = aggregates.total_assigned_assets;
  }
  if (reportType === 'departments' && aggregates?.total_assets != null) {
    summary.total_assets = aggregates.total_assets;
  }

  return res.status(200).json({
    success: true,
    message: 'Success',
    data: { rows, summary },
    pagination: { total, page, limit, totalPages }
  });
}

/** Inventory / asset-status preview: page of rows + full-filter summary aggregates. Exports omit page. */
async function sendPaginatedInventoryReport(res, reportType, filters, query) {
  return sendPaginatedListReport(res, reportType, filters, query, {
    fetchRows: (f) => InventoryModel.getAll(f),
    fetchAggregates: (f) => InventoryModel.getFilterAggregates(f)
  });
}

/** Custodian selected a department outside their scope — match inventory empty behavior. */
function rowsForReportFilters(filters, rows) {
  if (filters?.department_scope_mismatch) {
    return [];
  }
  return rows;
}

const ReportController = {
  async getFilterOptions(req, res) {
    try {
      const scope = getReportAccessScope(req.session.user);
      const dbMaterials = await InventoryModel.getDistinctMaterials();
      const defaultMaterials = [
        'Metal', 'Plastic', 'Wood', 'Paper', 'Glass',
        'Fabric', 'Rubber', 'Electronic', 'Composite', 'Other'
      ];
      const materials = [...new Set([...defaultMaterials, ...dbMaterials])].sort();

      let custodianSql = `
        SELECT u.id, u.full_name
        FROM users u
        JOIN roles r ON u.role_id = r.id
        WHERE u.is_active = 1 AND r.name = 'Custodian'`;
      const custodianParams = [];
      if (scope?.type === 'department' && scope.departmentId) {
        custodianSql += ' AND u.assigned_department_id = ?';
        custodianParams.push(scope.departmentId);
      }
      custodianSql += ' ORDER BY u.full_name ASC';
      const [custodianRows] = await pool.query(custodianSql, custodianParams);

      let departmentSql = 'SELECT id, name FROM departments WHERE is_archived = 0';
      const departmentParams = [];
      if (scope?.type === 'department' && scope.departmentId) {
        departmentSql += ' AND id = ?';
        departmentParams.push(scope.departmentId);
      }
      departmentSql += ' ORDER BY name ASC';
      const [departmentRows] = await pool.query(departmentSql, departmentParams);

      sendSuccess(res, {
        materials,
        custodians: custodianRows,
        departments: departmentRows,
        statuses: [
          'Available',
          'Borrowed',
          'Under Maintenance',
          'Disposed'
        ],
        conditions: [...CONDITION_OPTIONS]
      });
    } catch (err) {
      sendError(res, err.message, err.statusCode || 500);
    }
  },

  async getInventoryReport(req, res) {
    try {
      const filters = getInventoryReportFilters(req.query, req.session.user);
      await sendPaginatedInventoryReport(res, 'inventory', filters, req.query);
    } catch (err) {
      sendError(res, err.message, err.statusCode || 500);
    }
  },

  async getBorrowReport(req, res) {
    try {
      const filters = getBorrowReportFilters(req.query, req.session.user);
      await sendPaginatedListReport(res, 'borrow', filters, req.query, {
        fetchRows: (f) => BorrowModel.getAll(f),
        fetchAggregates: (f) => BorrowModel.getReportAggregates(f)
      });
    } catch (err) {
      sendError(res, err.message, err.statusCode || 500);
    }
  },

  async getReturnReport(req, res) {
    try {
      const filters = getScopedReportFilters(req.query, req.session.user);
      await sendPaginatedListReport(res, 'return', filters, req.query, {
        fetchRows: (f) => ReturnModel.getAll(f),
        fetchAggregates: (f) => ReturnModel.getReportAggregates(f)
      });
    } catch (err) {
      sendError(res, err.message, err.statusCode || 500);
    }
  },

  async getLowStockReport(req, res) {
    try {
      const filters = getScopedReportFilters(req.query, req.session.user);
      await sendReportSuccess(res, 'low-stock', [], filters);
    } catch (err) {
      sendError(res, err.message, err.statusCode || 500);
    }
  },

  async getSupplierReport(req, res) {
    try {
      const filters = getFilters(req.query);
      if (filters.supplier_name && !filters.name) {
        filters.name = filters.supplier_name;
      }
      await sendPaginatedListReport(res, 'supplier', filters, req.query, {
        fetchRows: (f) => SupplierModel.getAll(f),
        fetchAggregates: (f) => SupplierModel.getReportAggregates(f)
      });
    } catch (err) {
      sendError(res, err.message, err.statusCode || 500);
    }
  },

  async getTransferReport(req, res) {
    try {
      const filters = getScopedReportFilters(req.query, req.session.user);
      await sendPaginatedListReport(res, 'transfers', filters, req.query, {
        fetchRows: (f) => TransferModel.getAll(f),
        fetchAggregates: (f) => TransferModel.getReportAggregates(f)
      });
    } catch (err) { sendError(res, err.message, err.statusCode || 500); }
  },

  async getMaintenanceReport(req, res) {
    try {
      const filters = getScopedReportFilters(req.query, req.session.user);
      await sendPaginatedListReport(res, 'maintenance', filters, req.query, {
        fetchRows: (f) => MaintenanceModel.getAll(f),
        fetchAggregates: (f) => MaintenanceModel.getReportAggregates(f)
      });
    } catch (err) { sendError(res, err.message, err.statusCode || 500); }
  },

  async getDisposalReport(req, res) {
    try {
      const filters = getScopedReportFilters(req.query, req.session.user);
      await sendPaginatedListReport(res, 'disposals', filters, req.query, {
        fetchRows: (f) => DisposalModel.getAll(f),
        fetchAggregates: (f) => DisposalModel.getReportAggregates(f)
      });
    } catch (err) { sendError(res, err.message, err.statusCode || 500); }
  },

  async getDepartmentReport(req, res) {
    try {
      const filters = getScopedReportFilters(req.query, req.session.user);

      const fetchDepartmentRows = async (f) => {
        if (f.department_scope_mismatch) return emptyListResult(f);
        const scope = f.scope;
        let whereSql = ' WHERE d.is_archived = 0';
        const params = [];
        if (scope?.type === 'department' && scope.departmentId) {
          whereSql += ' AND d.id = ?';
          params.push(scope.departmentId);
        }
        if (f.department_id) {
          whereSql += ' AND d.id = ?';
          params.push(f.department_id);
        }
        if (f.name) {
          whereSql += ' AND d.name LIKE ?';
          params.push(`%${f.name}%`);
        }
        if (f.code) {
          whereSql += ' AND d.code LIKE ?';
          params.push(`%${f.code}%`);
        }
        if (f.department_head) {
          whereSql += ' AND d.department_head LIKE ?';
          params.push(`%${f.department_head}%`);
        }
        const joins = `
          FROM departments d
          LEFT JOIN users u ON d.custodian_id = u.id`;
        const selectSql = `
          SELECT d.*, u.full_name AS custodian_name,
                 (SELECT COUNT(*) FROM inventory_items i WHERE i.department_id = d.id AND i.is_archived = 0 AND i.status != 'Disposed') AS asset_count
          ${joins}${whereSql}`;
        const countSql = `SELECT COUNT(*) AS total ${joins}${whereSql}`;
        return queryWithOptionalPagination(pool, {
          selectSql,
          countSql,
          params,
          orderBy: 'ORDER BY d.name',
          filters: f
        });
      };

      const fetchDepartmentAggregates = async (f) => {
        const rows = normalizeListRows(await fetchDepartmentRows({
          ...f,
          paginated: false,
          page: undefined,
          limit: undefined
        }));
        const status_breakdown = {};
        const department_breakdown = {};
        let total_assets = 0;
        rows.forEach((row) => {
          const status = row.status || 'Unspecified';
          status_breakdown[status] = (status_breakdown[status] || 0) + 1;
          const name = row.name || 'Unspecified';
          department_breakdown[name] = (department_breakdown[name] || 0) + 1;
          total_assets += Number(row.asset_count || 0);
        });
        return {
          total: rows.length,
          status_breakdown,
          department_breakdown,
          total_assets
        };
      };

      await sendPaginatedListReport(res, 'departments', filters, req.query, {
        fetchRows: fetchDepartmentRows,
        fetchAggregates: fetchDepartmentAggregates
      });
    } catch (err) { sendError(res, err.message, err.statusCode || 500); }
  },

  async getAssetStatusReport(req, res) {
    try {
      const filters = getInventoryReportFilters(req.query, req.session.user);
      await sendPaginatedInventoryReport(res, 'asset-status', filters, req.query);
    } catch (err) { sendError(res, err.message, err.statusCode || 500); }
  },

  async getCustodianReport(req, res) {
    try {
      const filters = getScopedReportFilters(req.query, req.session.user);

      const buildCustodianParts = (f) => {
        let whereSql = ' WHERE i.status != \'Disposed\'';
        const params = [];
        const scope = f.scope;
        if (scope?.type === 'department' && scope.departmentId) {
          whereSql += ' AND i.department_id = ?';
          params.push(scope.departmentId);
        }
        if (f.department_id) {
          whereSql += ' AND i.department_id = ?';
          params.push(f.department_id);
        }
        if (f.custodian_name) {
          whereSql += ' AND u.full_name LIKE ?';
          params.push(`%${f.custodian_name}%`);
        }
        if (f.custodian_id) {
          whereSql += ' AND u.id = ?';
          params.push(f.custodian_id);
        }
        if (f.email) {
          whereSql += ' AND u.email LIKE ?';
          params.push(`%${f.email}%`);
        }
        const joins = `
          FROM inventory_items i
          JOIN users u ON i.custodian_id = u.id`;
        return { joins, whereSql, params };
      };

      const fetchCustodianRows = async (f) => {
        if (f.department_scope_mismatch) return emptyListResult(f);
        const { joins, whereSql, params } = buildCustodianParts(f);
        const selectSql = `
          SELECT u.full_name AS custodian_name, u.email,
                 COUNT(i.id) AS assigned_assets
          ${joins}${whereSql}
          GROUP BY u.id, u.full_name, u.email`;
        // Count grouped custodians
        const countSql = `
          SELECT COUNT(*) AS total FROM (
            SELECT u.id ${joins}${whereSql} GROUP BY u.id
          ) scoped_custodians`;
        return queryWithOptionalPagination(pool, {
          selectSql,
          countSql,
          params,
          orderBy: 'ORDER BY assigned_assets DESC',
          filters: f
        });
      };

      const fetchCustodianAggregates = async (f) => {
        if (f.department_scope_mismatch) {
          return { total: 0, status_breakdown: {}, department_breakdown: {}, total_assigned_assets: 0 };
        }
        const { joins, whereSql, params } = buildCustodianParts(f);
        const [countRows] = await pool.query(
          `SELECT COUNT(*) AS total FROM (
             SELECT u.id ${joins}${whereSql} GROUP BY u.id
           ) scoped_custodians`,
          params
        );
        const [assetRows] = await pool.query(
          `SELECT COUNT(i.id) AS total_assets ${joins}${whereSql}`,
          params
        );
        return {
          total: Number(countRows[0]?.total || 0),
          status_breakdown: {},
          department_breakdown: {},
          total_assigned_assets: Number(assetRows[0]?.total_assets || 0)
        };
      };

      await sendPaginatedListReport(res, 'custodians', filters, req.query, {
        fetchRows: fetchCustodianRows,
        fetchAggregates: fetchCustodianAggregates
      });
    } catch (err) { sendError(res, err.message, err.statusCode || 500); }
  },

  async exportPDF(req, res) {
    try {
      const { type } = req.params;
      let reportFilters = getFilters(req.query);
      let title, headers, rows, sourceRows = [];

      switch (type) {
        case 'inventory': {
          reportFilters = getInventoryReportFilters(req.query, req.session.user);
          const items = await InventoryModel.getAll(reportFilters);
          sourceRows = items;
          title = 'Inventory Report';
          break;
        }
        case 'borrow': {
          reportFilters = getBorrowReportFilters(req.query, req.session.user);
          const data = reportFilters.department_scope_mismatch ? [] : await BorrowModel.getAll(reportFilters);
          sourceRows = data;
          title = 'Borrow Report';
          headers = ['Code', 'Borrower', 'Department', 'Date', 'Status'];
          rows = data.map(b => [b.transaction_code, b.borrower_name, b.borrower_department, b.borrow_date, b.status]);
          break;
        }
        case 'return': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          const data = reportFilters.department_scope_mismatch ? [] : await ReturnModel.getAll(reportFilters);
          sourceRows = data;
          title = 'Process Return Report';
          headers = ['Code', 'Borrow Code', 'Processed By', 'Process Return Date', 'Condition'];
          rows = data.map(r => [r.transaction_code, r.borrow_code, r.returned_by_name, r.return_date, r.condition]);
          break;
        }
        case 'low-stock': {
          title = 'Low Stock Report';
          headers = ['Note'];
          rows = [['Low stock reporting is not available for property-based inventory.']];
          sourceRows = [];
          break;
        }
        case 'supplier': {
          const suppliers = await SupplierModel.getAll(reportFilters);
          sourceRows = suppliers;
          title = 'Supplier Report';
          headers = ['Name', 'Contact', 'Phone', 'Email'];
          rows = suppliers.map(s => [s.name, s.contact_person, s.phone, s.email]);
          break;
        }
        case 'transfers': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          const data = reportFilters.department_scope_mismatch ? [] : await TransferModel.getAll(reportFilters);
          sourceRows = data;
          title = 'Transfer Report';
          headers = ['Code', 'Item', 'Property Tag', 'From Dept', 'To Dept', 'Status', 'Requested By'];
          rows = data.map(t => [t.transaction_code, t.item_name, t.property_tag, t.from_department_name, t.to_department_name, t.status, t.requested_by_name]);
          break;
        }
        case 'maintenance': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          const data = reportFilters.department_scope_mismatch ? [] : await MaintenanceModel.getAll(reportFilters);
          sourceRows = data;
          title = 'Maintenance Report';
          headers = ['Item', 'Property Tag', 'Type', 'Scheduled', 'Completed', 'Status', 'Provider'];
          rows = data.map(m => [m.item_name, m.property_tag, m.maintenance_type, m.scheduled_date, m.completed_date, m.status, m.service_provider]);
          break;
        }
        case 'disposals': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          const data = reportFilters.department_scope_mismatch ? [] : await DisposalModel.getAll(reportFilters);
          sourceRows = data;
          title = 'Disposal Report';
          headers = ['Code', 'Item', 'Property Tag', 'Qty', 'Method', 'Status', 'Requested By'];
          rows = data.map(d => [d.transaction_code, d.item_name, d.property_tag, d.quantity, d.disposal_method, d.status, d.requested_by_name]);
          break;
        }
        case 'asset-status': {
          reportFilters = getInventoryReportFilters(req.query, req.session.user);
          const items = await InventoryModel.getAll(reportFilters);
          sourceRows = items;
          title = 'Asset Status Report';
          break;
        }
        case 'departments': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          title = 'Department Report';
          headers = ['Name', 'Code', 'Head', 'Custodian', 'Assets', 'Status'];
          if (reportFilters.department_scope_mismatch) {
            sourceRows = [];
            rows = [];
            break;
          }
          const scope = reportFilters.scope;
          let sql = `
            SELECT d.*, u.full_name AS custodian_name,
                   (SELECT COUNT(*) FROM inventory_items i WHERE i.department_id = d.id AND i.is_archived = 0 AND i.status != 'Disposed') AS asset_count
            FROM departments d LEFT JOIN users u ON d.custodian_id = u.id
            WHERE d.is_archived = 0`;
          const params = [];
          if (scope?.type === 'department' && scope.departmentId) {
            sql += ' AND d.id = ?';
            params.push(scope.departmentId);
          }
          if (reportFilters.department_id) {
            sql += ' AND d.id = ?';
            params.push(reportFilters.department_id);
          }
          if (reportFilters.name) {
            sql += ' AND d.name LIKE ?';
            params.push(`%${reportFilters.name}%`);
          }
          sql += ' ORDER BY d.name';
          const [deptRows] = await pool.query(sql, params);
          sourceRows = deptRows;
          rows = deptRows.map(d => [d.name, d.code, d.department_head, d.custodian_name, d.asset_count, d.status]);
          break;
        }
        case 'custodians': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          title = 'Custodian Report';
          headers = ['Custodian', 'Email', 'Assigned Assets'];
          if (reportFilters.department_scope_mismatch) {
            sourceRows = [];
            rows = [];
            break;
          }
          const scope = reportFilters.scope;
          let sql = `
            SELECT u.full_name AS custodian_name, u.email,
                   COUNT(i.id) AS assigned_assets
            FROM inventory_items i
            JOIN users u ON i.custodian_id = u.id
            WHERE i.status != 'Disposed'`;
          const params = [];
          if (scope?.type === 'department' && scope.departmentId) {
            sql += ' AND i.department_id = ?';
            params.push(scope.departmentId);
          }
          if (reportFilters.department_id) {
            sql += ' AND i.department_id = ?';
            params.push(reportFilters.department_id);
          }
          sql += ` GROUP BY u.id, u.full_name, u.email ORDER BY assigned_assets DESC`;
          const [custRows] = await pool.query(sql, params);
          sourceRows = custRows;
          rows = custRows.map(c => [c.custodian_name, c.email, c.assigned_assets]);
          break;
        }
        default:
          return sendError(res, 'Invalid report type', 400);
      }

      const headerMeta = await buildExportHeaderMeta(
        type,
        sourceRows,
        reportFilters,
        req.session.user
      );
      if (title) headerMeta.title = title;

      if (type === 'inventory' || type === 'asset-status') {
        ({ headers, rows } = buildInventoryExportTable(sourceRows, headerMeta, {
          includeClassificationConditionStatus: type !== 'inventory'
        }));
      }

      if (!headers || !rows) {
        return sendError(res, 'Unable to build report export', 500);
      }

      const useLandscape = shouldUseLandscape(headers);
      const doc = new PDFDocument({
        margin: 40,
        size: 'LETTER',
        layout: useLandscape ? 'landscape' : 'portrait'
      });
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="${type}-report.pdf"`);
      doc.pipe(res);

      writePdfExportHeader(doc, headerMeta);

      const startX = doc.page.margins.left;
      const usableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
      const colWidth = usableWidth / headers.length;
      const cellPadding = 4;
      const pageBottom = doc.page.height - doc.page.margins.bottom;
      doc.fontSize(8);

      let headerHeight = 18;
      doc.font('Helvetica-Bold');
      headers.forEach((header) => {
        const height = doc.heightOfString(header, { width: colWidth - cellPadding }) + 8;
        headerHeight = Math.max(headerHeight, height);
      });

      let y = doc.y;
      headers.forEach((header, i) => {
        doc.text(header, startX + i * colWidth, y, { width: colWidth - cellPadding });
      });
      y += headerHeight;
      doc.moveTo(startX, y).lineTo(doc.page.width - doc.page.margins.right, y).stroke();
      y += 5;

      const drawHeaderRow = () => {
        doc.font('Helvetica-Bold');
        headers.forEach((header, i) => {
          doc.text(header, startX + i * colWidth, y, { width: colWidth - cellPadding });
        });
        y += headerHeight;
        doc.moveTo(startX, y).lineTo(doc.page.width - doc.page.margins.right, y).stroke();
        y += 5;
        doc.font('Helvetica');
      };

      rows.forEach((row) => {
        doc.font('Helvetica');
        let rowHeight = 16;
        row.forEach((cell) => {
          const height = doc.heightOfString(String(cell ?? ''), { width: colWidth - cellPadding }) + 8;
          rowHeight = Math.max(rowHeight, height);
        });

        if (y + rowHeight > pageBottom) {
          doc.addPage();
          y = doc.page.margins.top;
          drawHeaderRow();
        }

        row.forEach((cell, i) => {
          doc.text(String(cell ?? ''), startX + i * colWidth, y, { width: colWidth - cellPadding });
        });
        y += rowHeight;
      });

      doc.end();
    } catch (err) {
      sendError(res, err.message, err.statusCode || 500);
    }
  },

  async exportExcel(req, res) {
    try {
      const { type } = req.params;
      const workbook = new ExcelJS.Workbook();
      workbook.creator = 'Cavite Institute Property Management System';
      const sheet = workbook.addWorksheet('Report');

      let title;
      let headers;
      let rows = [];
      let sourceRows = [];
      let reportFilters = getFilters(req.query);

      switch (type) {
        case 'inventory': {
          reportFilters = getInventoryReportFilters(req.query, req.session.user);
          const items = await InventoryModel.getAll(reportFilters);
          sourceRows = items;
          title = 'Inventory Report';
          break;
        }
        case 'borrow': {
          reportFilters = getBorrowReportFilters(req.query, req.session.user);
          const data = reportFilters.department_scope_mismatch ? [] : await BorrowModel.getAll(reportFilters);
          sourceRows = data;
          title = 'Borrow Report';
          headers = ['Code', 'Borrower', 'Department', 'Purpose', 'Borrow Date', 'Expected Return', 'Status'];
          rows = data.map(b => [b.transaction_code, b.borrower_name, b.borrower_department, b.purpose, b.borrow_date, b.expected_return_date, b.status]);
          break;
        }
        case 'return': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          const data = reportFilters.department_scope_mismatch ? [] : await ReturnModel.getAll(reportFilters);
          sourceRows = data;
          title = 'Process Return Report';
          headers = ['Code', 'Borrow Code', 'Processed By', 'Process Return Date', 'Condition', 'Notes'];
          rows = data.map(r => [r.transaction_code, r.borrow_code, r.returned_by_name, r.return_date, r.condition, r.notes]);
          break;
        }
        case 'low-stock': {
          title = 'Low Stock Report';
          headers = ['Note'];
          rows = [['Low stock reporting is not available for property-based inventory.']];
          sourceRows = [];
          break;
        }
        case 'supplier': {
          const suppliers = await SupplierModel.getAll(reportFilters);
          sourceRows = suppliers;
          title = 'Supplier Report';
          headers = ['Name', 'Contact Person', 'Phone', 'Email', 'Address'];
          rows = suppliers.map(s => [s.name, s.contact_person, s.phone, s.email, s.address]);
          break;
        }
        case 'transfers': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          const data = reportFilters.department_scope_mismatch ? [] : await TransferModel.getAll(reportFilters);
          sourceRows = data;
          title = 'Transfer Report';
          headers = ['Code', 'Item', 'Property Tag', 'From Dept', 'To Dept', 'Status', 'Requested By'];
          rows = data.map(t => [t.transaction_code, t.item_name, t.property_tag, t.from_department_name, t.to_department_name, t.status, t.requested_by_name]);
          break;
        }
        case 'maintenance': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          const data = reportFilters.department_scope_mismatch ? [] : await MaintenanceModel.getAll(reportFilters);
          sourceRows = data;
          title = 'Maintenance Report';
          headers = ['Item', 'Property Tag', 'Type', 'Scheduled', 'Completed', 'Status', 'Provider'];
          rows = data.map(m => [m.item_name, m.property_tag, m.maintenance_type, m.scheduled_date, m.completed_date, m.status, m.service_provider]);
          break;
        }
        case 'disposals': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          const data = reportFilters.department_scope_mismatch ? [] : await DisposalModel.getAll(reportFilters);
          sourceRows = data;
          title = 'Disposal Report';
          headers = ['Code', 'Item', 'Property Tag', 'Qty', 'Method', 'Status', 'Requested By'];
          rows = data.map(d => [d.transaction_code, d.item_name, d.property_tag, d.quantity, d.disposal_method, d.status, d.requested_by_name]);
          break;
        }
        case 'asset-status': {
          reportFilters = getInventoryReportFilters(req.query, req.session.user);
          const items = await InventoryModel.getAll(reportFilters);
          sourceRows = items;
          title = 'Asset Status Report';
          break;
        }
        case 'departments': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          title = 'Department Report';
          headers = ['Name', 'Code', 'Head', 'Custodian', 'Assets', 'Status'];
          if (reportFilters.department_scope_mismatch) {
            sourceRows = [];
            rows = [];
            break;
          }
          const scope = reportFilters.scope;
          let sql = `
            SELECT d.*, u.full_name AS custodian_name,
                   (SELECT COUNT(*) FROM inventory_items i WHERE i.department_id = d.id AND i.is_archived = 0 AND i.status != 'Disposed') AS asset_count
            FROM departments d LEFT JOIN users u ON d.custodian_id = u.id
            WHERE d.is_archived = 0`;
          const params = [];
          if (scope?.type === 'department' && scope.departmentId) {
            sql += ' AND d.id = ?';
            params.push(scope.departmentId);
          }
          if (reportFilters.department_id) {
            sql += ' AND d.id = ?';
            params.push(reportFilters.department_id);
          }
          if (reportFilters.name) {
            sql += ' AND d.name LIKE ?';
            params.push(`%${reportFilters.name}%`);
          }
          sql += ' ORDER BY d.name';
          const [deptRows] = await pool.query(sql, params);
          sourceRows = deptRows;
          rows = deptRows.map(d => [d.name, d.code, d.department_head, d.custodian_name, d.asset_count, d.status]);
          break;
        }
        case 'custodians': {
          reportFilters = getScopedReportFilters(req.query, req.session.user);
          title = 'Custodian Report';
          headers = ['Custodian', 'Email', 'Assigned Assets'];
          if (reportFilters.department_scope_mismatch) {
            sourceRows = [];
            rows = [];
            break;
          }
          const scope = reportFilters.scope;
          let sql = `
            SELECT u.full_name AS custodian_name, u.email,
                   COUNT(i.id) AS assigned_assets
            FROM inventory_items i
            JOIN users u ON i.custodian_id = u.id
            WHERE i.status != 'Disposed'`;
          const params = [];
          if (scope?.type === 'department' && scope.departmentId) {
            sql += ' AND i.department_id = ?';
            params.push(scope.departmentId);
          }
          if (reportFilters.department_id) {
            sql += ' AND i.department_id = ?';
            params.push(reportFilters.department_id);
          }
          sql += ` GROUP BY u.id, u.full_name, u.email ORDER BY assigned_assets DESC`;
          const [custRows] = await pool.query(sql, params);
          sourceRows = custRows;
          rows = custRows.map(c => [c.custodian_name, c.email, c.assigned_assets]);
          break;
        }
        default:
          return sendError(res, 'Invalid report type', 400);
      }

      const headerMeta = await buildExportHeaderMeta(
        type,
        sourceRows,
        reportFilters,
        req.session.user
      );
      if (title) headerMeta.title = title;

      if (type === 'inventory' || type === 'asset-status') {
        ({ headers, rows } = buildInventoryExportTable(sourceRows, headerMeta));
      }

      if (!headers || !Array.isArray(rows)) {
        return sendError(res, 'Unable to build report export', 500);
      }

      writeExcelExportHeader(sheet, headerMeta);

      const tableHeaderRow = sheet.addRow(headers);
      tableHeaderRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      tableHeaderRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF800000' } };
      tableHeaderRow.alignment = { vertical: 'middle', wrapText: true };

      rows.forEach((row) => {
        const excelRow = sheet.addRow(row);
        excelRow.alignment = { vertical: 'middle', wrapText: true };
      });

      autofitExcelColumns(sheet);

      const useLandscape = shouldUseLandscape(headers);
      sheet.pageSetup = {
        fitToPage: true,
        fitToWidth: 1,
        fitToHeight: 0,
        orientation: useLandscape ? 'landscape' : 'portrait',
        margins: { left: 0.5, right: 0.5, top: 0.5, bottom: 0.5, header: 0.3, footer: 0.3 }
      };

      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename="${type}-report.xlsx"`);
      await workbook.xlsx.write(res);
      res.end();
    } catch (err) {
      sendError(res, err.message, err.statusCode || 500);
    }
  }
};

module.exports = ReportController;
