let documents = [];

async function initDocumentsPage() {
  const user = await initLayout('documents');
  if (!user) return;

  document.getElementById('pageContent').innerHTML = `
    <div class="page-header">
      <h1>Document History</h1>
      <p>View, preview, print, and download previously generated official documents</p>
    </div>
    <div class="content-card">
      <div class="filters-bar">
        <input type="text" class="form-control-custom" id="searchInput" placeholder="Search by document number...">
        <select class="form-control-custom" id="filterType">
          <option value="">All Types</option>
          <option>PAR</option>
          <option>GRN</option>
          <option>RDF</option>
          <option>ABL</option>
          <option>TRF</option>
          <option>SAL</option>
        </select>
      </div>
      <div class="table-responsive" id="documentsTable">
        <div class="loading-spinner"><i class="bi bi-arrow-repeat"></i> Loading...</div>
      </div>
    </div>
  `;

  document.getElementById('searchInput').addEventListener('input', debounce(loadDocuments, 300));
  document.getElementById('filterType').addEventListener('change', loadDocuments);
  await loadDocuments();
}

async function loadDocuments() {
  const params = {};
  const search = document.getElementById('searchInput')?.value;
  const type = document.getElementById('filterType')?.value;
  if (search) params.search = search;
  if (type) params.document_type = type;

  try {
    const res = await API.getDocuments(params);
    documents = res?.data || [];
    renderDocuments();
  } catch (err) {
    showToast(err.message, 'error');
  }
}

function renderDocuments() {
  const el = document.getElementById('documentsTable');
  if (!documents.length) {
    el.innerHTML = '<div class="empty-state"><i class="bi bi-file-earmark-text"></i>No documents found</div>';
    return;
  }

  el.innerHTML = `
    <table class="data-table">
      <thead>
        <tr>
          <th>Document No.</th><th>Type</th><th>Related Module</th><th>Generated By</th><th>Generated Date</th><th>Actions</th>
        </tr>
      </thead>
      <tbody>
        ${documents.map(d => `
          <tr>
            <td>${d.document_number}</td>
            <td>${d.document_type}</td>
            <td>${d.related_module || '-'} #${d.related_transaction_id || '-'}</td>
            <td>${d.generated_by_name || '-'}</td>
            <td>${formatDate(d.generated_at)}</td>
            <td style="white-space:nowrap;">
              <button class="btn-icon" onclick="API.openDocumentPreview(${d.id})" title="View" aria-label="View"><i class="bi bi-eye"></i></button>
              <button class="btn-icon" onclick="API.downloadDocumentPdf(${d.id})" title="Download PDF"><i class="bi bi-file-pdf"></i></button>
              <button class="btn-icon" onclick="window.open('/pages/document-preview.html?id=${d.id}','_blank'); setTimeout(()=>window.print(), 500)" title="Print"><i class="bi bi-printer"></i></button>
            </td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  `;
}

document.addEventListener('DOMContentLoaded', initDocumentsPage);
