let documents = [];
let documentsTableSelection = null;

async function initDocumentsPage() {
  const user = await initLayout('documents');
  if (!user) return;

  document.getElementById('pageContent').innerHTML = `
    <div class="page-header">
      <h1>Document History</h1>
      <p>View, preview, print, and download previously generated official documents</p>
    </div>
    <div class="content-card">
      <div class="filters-bar">
        <input type="text" class="form-control-custom" id="searchInput" placeholder="Search by document number...">
        <select class="form-control-custom" id="filterType">
          <option value="">All Types</option>
          <option>PAR</option>
          <option>GRN</option>
          <option>RDF</option>
          <option>ABL</option>
          <option>TRF</option>
          <option>SAL</option>
        </select>
      </div>
      <div class="table-responsive" id="documentsTable">
        <div class="loading-spinner"><i class="bi bi-arrow-repeat"></i> Loading...</div>
      </div>
    </div>
  `;

  document.getElementById('searchInput').addEventListener('input', debounce(loadDocuments, 300));
  document.getElementById('filterType').addEventListener('change', loadDocuments);
  initActionMenus();
  initDocumentsTableSelection();
  await loadDocuments();
  initSearchableSelects(document.getElementById('pageContent'));
}

async function loadDocuments() {
  const params = {};
  const search = document.getElementById('searchInput')?.value;
  const type = document.getElementById('filterType')?.value;
  if (search) params.search = search;
  if (type) params.document_type = type;

  try {
    const res = await API.getDocuments(params);
    documents = res?.data || [];
    renderDocuments();
  } catch (err) {
    showToast(err.message, 'error');
  }
}

function initDocumentsTableSelection() {
  documentsTableSelection = createTableSelection({
    container: 'documentsTable',
    getRowId: (doc) => doc.id,
    getVisibleRows: () => documents,
    bulkActions: [
      {
        id: 'download',
        label: 'Download Selected',
        icon: 'bi-file-pdf',
        onClick: bulkDownloadDocuments
      }
    ]
  });
}

function bulkDownloadDocuments(_ids, rows) {
  rows.forEach((doc) => API.downloadDocumentPdf(doc.id));
  showToast(`Started download for ${rows.length} document(s)`);
}

function renderDocumentActions(d) {
  return renderActionMenuCell(`document-actions-${d.id}`, [
    { label: 'View', icon: 'bi-eye', handler: `API.openDocumentPreview(${d.id})` },
    { label: 'Download PDF', icon: 'bi-file-pdf', handler: `API.downloadDocumentPdf(${d.id})` },
    { label: 'Print', icon: 'bi-printer', handler: `window.open('/pages/document-preview.html?id=${d.id}','_blank'); setTimeout(()=>window.print(), 500)` }
  ]);
}

function renderDocuments() {
  const el = document.getElementById('documentsTable');
  documentsTableSelection?.pruneHiddenSelections();

  if (!documents.length) {
    el.innerHTML = '<div class="empty-state"><i class="bi bi-file-earmark-text"></i>No documents found</div>';
    documentsTableSelection?.bindAfterRender(el);
    return;
  }

  el.innerHTML = `
    <table class="data-table">
      <thead>
        <tr>
          ${documentsTableSelection?.renderCheckboxHeader() || ''}
          <th>Document No.</th><th>Type</th><th>Related Module</th><th>Generated By</th><th>Generated Date</th><th>Actions</th>
        </tr>
      </thead>
      <tbody>
        ${documents.map(d => `
          <tr${documentsTableSelection?.renderRowAttrs(d) || ''}>
            ${documentsTableSelection?.renderCheckboxCell(d) || ''}
            <td>${d.document_number}</td>
            <td>${d.document_type}</td>
            <td>${d.related_module || '-'} #${d.related_transaction_id || '-'}</td>
            <td>${d.generated_by_name || '-'}</td>
            <td>${formatDate(d.generated_at)}</td>
            <td>${renderDocumentActions(d)}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  `;
  finishTableRender(el);
  documentsTableSelection?.bindAfterRender(el);
}

document.addEventListener('DOMContentLoaded', initDocumentsPage);
